### ISSUE TITLE
Does not work on Debian Jessie

### ISSUE THREAD

**Issue by phenomax** [izolate/html2pug#17]
I installed the most recent version of html2pug from npm (1.0.0) and used NodeJS v6.11.1.
When running `html2pug -f <file>.html` the following error is being thrown

`module.exports = async (sourceHtml, opts = {}) => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/html2pug/src/cli.js:6:18)`

This error can also be reproduced on Windows 10 using NodeJs v6.10.3 and npm 3.10.10

**Comment by izolate** [comment]
@phenomax This is not platform specific. Node `6.x` doesn't support async functions. Please update to at least Node `7.6` to use this library.

Highly recommend [`nvm`](https://github.com/creationix/nvm) for switching between node versions.
