### ISSUE TITLE
The CLI does not works

### ISSUE THREAD

**Issue by demsking** [izolate/html2pug#26]
REPL does not allow top-level Async Function. So the CLI code throws an error:

```js
async function main ({ fragment, needsHelp, showVersion, tabs }) {
  const stdin = await getStdin()

  if (showVersion) {
    return console.log(version)
  }

  if (needsHelp || !stdin) {
    return console.log(help)
  }

  const pug = html2pug(stdin, { tabs, fragment })
  console.log(pug)
}
```

```shell
$ html2pug < src/template.html > src/template.pug
/home/demsking/.nvm/versions/node/v6.11.2/lib/node_modules/html2pug/src/cli.js:30
async function main ({ fragment, needsHelp, showVersion, tabs }) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by izolate** [comment]
@demsking Your Node version (`6.11`) doesn't support async functions. Please upgrade to `7.6` or higher to use this library.

**Comment by demsking** [comment]
The problem is that in some companies, we only use the LTS version of NodeJS and users don't have rights to upgrade to a newer version. That's why I made this change.

**Comment by izolate** [comment]
@demsking I appreciate that, but the currently active LTS is [8.x](https://github.com/nodejs/Release#release-schedule1) with native async/await support

**Comment by demsking** [comment]
Yes, it was just released yesterday... The time companies upgrade.

**Comment by demsking** [comment]
Dont worry its ok. I finally used the `pug` package for my use case.
